{"author":"dotnet-bot","ms.author":"dotnetcontent","manager":"wpickett","breadcrumb_path":"/dotnet/toc.json","ms.topic":"managed-reference","ms.prod":".net","search.ms_sitename":"Docs","search.ms_docsetname":"docs-internal","version":0,"locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","depot_name":"MSDN.docs-internal","original_ref_skeleton_git_url":"https://github.com/dotnet/docs-internal/blob/master/api/System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.yml","open_to_public_contributors":false,"api_name":["System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord..ctor","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.Clone","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.FaultSource","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.ToString","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.UnhandledException"],"api_location":["System.Activities.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord","System::Activities::Tracking::WorkflowInstanceUnhandledExceptionRecord","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.#ctor","System::Activities::Tracking::WorkflowInstanceUnhandledExceptionRecord::#ctor","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.Clone","System::Activities::Tracking::WorkflowInstanceUnhandledExceptionRecord::Clone","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.FaultSource","System::Activities::Tracking::WorkflowInstanceUnhandledExceptionRecord::FaultSource","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.ToString","System::Activities::Tracking::WorkflowInstanceUnhandledExceptionRecord::ToString","System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord.UnhandledException","System::Activities::Tracking::WorkflowInstanceUnhandledExceptionRecord::UnhandledException"],"dev_langs":["csharp"],"updated_at":"2017-03-29 05:54 AM","document_id":"c41824ce-1111-c0c4-21b2-cc596433c01e","content_git_url":"https://github.com/dotnet/docs-internal/blob/master/xml/System.Activities.Tracking/WorkflowInstanceUnhandledExceptionRecord.xml","layout":"Reference","pagetype":"Reference","title":"WorkflowInstanceUnhandledExceptionRecord class | Microsoft Docs","description":"Contains the data sent to a tracking participant by the run-time tracking infrastructure when a workflow instance encounters an unhandled exception.\n","toc_asset_id":"api/_splitted/System.Activities.Tracking/toc.json","toc_rel":"_splitted/System.Activities.Tracking/toc.json","source_url":"","ms.assetid":"System.Activities.Tracking.WorkflowInstanceUnhandledExceptionRecord","canonical_url":"https://ppe.docs.microsoft.com/en-us/dotnet/api/system.activities.tracking.workflowinstanceunhandledexceptionrecord","is_dynamic_rendering":true,"content_type":"application/json","publish_version":"{\"opbuild.templates.docs\":\"1.30.3\",\"commit_id\":\"057ab023328e07a54f8e20d9aa890a9d5f4d323b\",\"branch\":\"master\",\"opbuild.scripts\":\"1.30.3\",\"opbuild.htmltopdftool\":\"1.30.3\",\"opbuild.gitcontributorinformationresolver\":\"1.30.3\",\"opbuild_service\":\"1.30.128.0\",\"docfx.console\":\"2.15.1\",\"opbuild.resolvedependencyconsole\":\"1.30.3\",\"opbuild.schemavalidationconsole\":\"1.30.3\",\"opbuild.redirectionresolver\":\"1.30.3\",\"opbuild.templates.intellisense\":\"1.30.3\",\"dependencies\":[{\"branch\":\"preview\",\"path\":\"_themes\",\"url\":\"https://github.com/Microsoft/templates.docs.msft\",\"commit_id\":\"5642506923d4436865b06695d7f256cf61d3fd60\",\"opbuild.templates.common\":\"1.30.3\"},{\"branch\":\"master\",\"path\":\"_themes.pdf\",\"url\":\"https://github.com/Microsoft/templates.docs.msft.pdf\",\"commit_id\":\"ed2aa9642124365e156c2670dab210e368095ebd\",\"opbuild.templates.common\":\"1.30.3\"}]}"}