{"author":"dotnet-bot","ms.author":"dotnetcontent","manager":"wpickett","breadcrumb_path":"/dotnet-internal/toc.json","ms.topic":"managed-reference","ms.prod":".net","search.ms_sitename":"Docs","search.ms_docsetname":"docs-internal","version":0,"locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","depot_name":"MSDN.docs-internal","original_ref_skeleton_git_url":"https://github.com/dotnet/docs-internal/blob/master/api/System.Data.SqlClient.SqlException.yml","open_to_public_contributors":false,"api_name":["System.Data.SqlClient.SqlException","System.Data.SqlClient.SqlException.Class","System.Data.SqlClient.SqlException.ClientConnectionId","System.Data.SqlClient.SqlException.Errors","System.Data.SqlClient.SqlException.GetObjectData","System.Data.SqlClient.SqlException.LineNumber","System.Data.SqlClient.SqlException.Number","System.Data.SqlClient.SqlException.Procedure","System.Data.SqlClient.SqlException.Server","System.Data.SqlClient.SqlException.Source","System.Data.SqlClient.SqlException.State","System.Data.SqlClient.SqlException.ToString"],"api_location":["System.Data.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Data.SqlClient.SqlException","System::Data::SqlClient::SqlException","System.Data.SqlClient.SqlException.Class","System::Data::SqlClient::SqlException::Class","System.Data.SqlClient.SqlException.ClientConnectionId","System::Data::SqlClient::SqlException::ClientConnectionId","System.Data.SqlClient.SqlException.Errors","System::Data::SqlClient::SqlException::Errors","System.Data.SqlClient.SqlException.GetObjectData","System::Data::SqlClient::SqlException::GetObjectData","System.Data.SqlClient.SqlException.LineNumber","System::Data::SqlClient::SqlException::LineNumber","System.Data.SqlClient.SqlException.Number","System::Data::SqlClient::SqlException::Number","System.Data.SqlClient.SqlException.Procedure","System::Data::SqlClient::SqlException::Procedure","System.Data.SqlClient.SqlException.Server","System::Data::SqlClient::SqlException::Server","System.Data.SqlClient.SqlException.Source","System::Data::SqlClient::SqlException::Source","System.Data.SqlClient.SqlException.State","System::Data::SqlClient::SqlException::State","System.Data.SqlClient.SqlException.ToString","System::Data::SqlClient::SqlException::ToString"],"dev_langs":["csharp"],"updated_at":"2017-03-23 06:04 AM","document_id":"25e9e64a-faeb-782b-0719-fb23ef4bdc4d","content_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/xml/System.Data.SqlClient/SqlException.xml","layout":"Reference","pagetype":"Reference","title":"SqlException class | Microsoft Docs","description":"The exception that is thrown when SQL Server returns a warning or error. This class cannot be inherited.\n","toc_asset_id":"api/_splitted/System.Data.SqlClient/toc.json","toc_rel":"_splitted/System.Data.SqlClient/toc.json","source_url":"","ms.assetid":"System.Data.SqlClient.SqlException","canonical_url":"https://ppe.docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception","is_dynamic_rendering":true,"content_type":"application/json","publish_version":"{\"opbuild.templates.docs\":\"1.29.2\",\"commit_id\":\"4daaa1618c43f8b649d421fc60ed8e3aaba1cba7\",\"branch\":\"master\",\"opbuild.scripts\":\"1.29.2\",\"opbuild.htmltopdftool\":\"1.29.2\",\"opbuild.gitcontributorinformationresolver\":\"1.29.2\",\"opbuild_service\":\"1.29.123.0\",\"docfx.console\":\"2.14.1\",\"opbuild.resolvedependencyconsole\":\"1.29.2\",\"opbuild.schemavalidationconsole\":\"1.29.2\",\"opbuild.redirectionresolver\":\"1.29.2\",\"opbuild.templates.intellisense\":\"1.29.2\",\"dependencies\":[{\"branch\":\"preview\",\"path\":\"_themes\",\"url\":\"https://github.com/Microsoft/templates.docs.msft\",\"commit_id\":\"eff7969f07a808864b2febe5a48618a2674e22af\",\"opbuild.templates.common\":\"1.29.2\"},{\"branch\":\"master\",\"path\":\"_themes.pdf\",\"url\":\"https://github.com/Microsoft/templates.docs.msft.pdf\",\"commit_id\":\"b2158fbf2c62f32aff19e6f61397f4caa40b05f7\",\"opbuild.templates.common\":\"1.29.2\"}]}"}