{"author":"dotnet-bot","ms.author":"dotnetcontent","manager":"wpickett","breadcrumb_path":"/dotnet/toc.json","ms.topic":"managed-reference","ms.prod":".net","search.ms_sitename":"Docs","search.ms_docsetname":"docs-internal","version":0,"locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","depot_name":"MSDN.docs-internal","original_ref_skeleton_git_url":"https://github.com/dotnet/docs-internal/blob/master/api/System.Data.SqlClient.SqlException.yml","open_to_public_contributors":false,"api_name":["System.Data.SqlClient.SqlException","System.Data.SqlClient.SqlException.Class","System.Data.SqlClient.SqlException.ClientConnectionId","System.Data.SqlClient.SqlException.Errors","System.Data.SqlClient.SqlException.GetObjectData","System.Data.SqlClient.SqlException.LineNumber","System.Data.SqlClient.SqlException.Number","System.Data.SqlClient.SqlException.Procedure","System.Data.SqlClient.SqlException.Server","System.Data.SqlClient.SqlException.Source","System.Data.SqlClient.SqlException.State","System.Data.SqlClient.SqlException.ToString"],"api_location":["System.Data.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Data.SqlClient.SqlException","System::Data::SqlClient::SqlException","System.Data.SqlClient.SqlException.Class","System::Data::SqlClient::SqlException::Class","System.Data.SqlClient.SqlException.ClientConnectionId","System::Data::SqlClient::SqlException::ClientConnectionId","System.Data.SqlClient.SqlException.Errors","System::Data::SqlClient::SqlException::Errors","System.Data.SqlClient.SqlException.GetObjectData","System::Data::SqlClient::SqlException::GetObjectData","System.Data.SqlClient.SqlException.LineNumber","System::Data::SqlClient::SqlException::LineNumber","System.Data.SqlClient.SqlException.Number","System::Data::SqlClient::SqlException::Number","System.Data.SqlClient.SqlException.Procedure","System::Data::SqlClient::SqlException::Procedure","System.Data.SqlClient.SqlException.Server","System::Data::SqlClient::SqlException::Server","System.Data.SqlClient.SqlException.Source","System::Data::SqlClient::SqlException::Source","System.Data.SqlClient.SqlException.State","System::Data::SqlClient::SqlException::State","System.Data.SqlClient.SqlException.ToString","System::Data::SqlClient::SqlException::ToString"],"dev_langs":["csharp"],"updated_at":"2017-03-29 05:54 AM","document_id":"25e9e64a-faeb-782b-0719-fb23ef4bdc4d","content_git_url":"https://github.com/dotnet/docs-internal/blob/master/xml/System.Data.SqlClient/SqlException.xml","layout":"Reference","pagetype":"Reference","title":"SqlException class | Microsoft Docs","description":"The exception that is thrown when SQL Server returns a warning or error. This class cannot be inherited.\n","toc_asset_id":"api/_splitted/System.Data.SqlClient/toc.json","toc_rel":"_splitted/System.Data.SqlClient/toc.json","source_url":"","ms.assetid":"System.Data.SqlClient.SqlException","canonical_url":"https://ppe.docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception","is_dynamic_rendering":true,"content_type":"application/json","publish_version":"{\"opbuild.templates.docs\":\"1.30.3\",\"commit_id\":\"057ab023328e07a54f8e20d9aa890a9d5f4d323b\",\"branch\":\"master\",\"opbuild.scripts\":\"1.30.3\",\"opbuild.htmltopdftool\":\"1.30.3\",\"opbuild.gitcontributorinformationresolver\":\"1.30.3\",\"opbuild_service\":\"1.30.128.0\",\"docfx.console\":\"2.15.1\",\"opbuild.resolvedependencyconsole\":\"1.30.3\",\"opbuild.schemavalidationconsole\":\"1.30.3\",\"opbuild.redirectionresolver\":\"1.30.3\",\"opbuild.templates.intellisense\":\"1.30.3\",\"dependencies\":[{\"branch\":\"preview\",\"path\":\"_themes\",\"url\":\"https://github.com/Microsoft/templates.docs.msft\",\"commit_id\":\"5642506923d4436865b06695d7f256cf61d3fd60\",\"opbuild.templates.common\":\"1.30.3\"},{\"branch\":\"master\",\"path\":\"_themes.pdf\",\"url\":\"https://github.com/Microsoft/templates.docs.msft.pdf\",\"commit_id\":\"ed2aa9642124365e156c2670dab210e368095ebd\",\"opbuild.templates.common\":\"1.30.3\"}]}"}